[package]
name = "snow"
description = "Cerulean CLI (Wowzers!!)"
version = "0.1.0"
authors = ["_cry64 <them@dobutterfliescry.net>"]
edition = "2024"

[dependencies]
nix-bindings-expr = { git = "https://tearforge.net/cry/nixide" }
nix-bindings-flake = { git = "https://tearforge.net/cry/nixide" }
nix-bindings-fetchers = { git = "https://tearforge.net/cry/nixide" }
nix-bindings-store = { git = "https://tearforge.net/cry/nixide" }

indoc = "2"
anyhow = "1.0.102"

clap = { version = "4.5.60", features = ["derive"] }
log = "0.4.29"
fern = { version="0.7.1", features = ["colored"] }
humantime = "2.3.0"
